image: node:16-alpine

stages:
  - build
  - deploy

build_production:
  stage: build

  when: manual
  rules:
    - if: $CI_COMMIT_BRANCH == "main"

  before_script:
    - cat "$DOT_ENV_PROD" > "$(pwd)/.env"
    - apk add --no-cache git
  script:
    - npm install --legacy-peer-deps
    - CI=false npm run build
  artifacts:
    paths:
      - ./build
    untracked: false
    expire_in: 1 day

deploy_S3_prod:
  stage: deploy
  image: registry.gitlab.com/gitlab-org/cloud-deploy/aws-base:latest

  rules:
    - if: $CI_COMMIT_BRANCH == "main"

  needs:
    - build_production

  services:
    - docker:dind

  script:
    - aws --version
    - aws s3 sync --delete ./build s3://$S3_BUCKET_PROD
    - aws cloudfront create-invalidation --distribution-id $CLOUDFRONT_ID_PROD --paths '/*'
